-- 관리자 계정
-- 테이블
	CREATE TABLE DG_ADMIN(
		ADMINID VARCHAR2(500),
		ADMINPW VARCHAR2(500),
		CONSTRAINT DG_ADMIN_PK PRIMARY KEY(ADMINID)
	);

	INSERT INTO DG_ADMIN VALUES('admin', '1234');

	SELECT * FROM DG_ADMIN;