-- 거래내역 테이블
-- 시퀀스
	CREATE SEQUENCE DG_TRADE_SEQ;
-- 테이블 
	CREATE TABLE DG_TRADE(
		TRADENUM NUMBER,
		USERID VARCHAR2(200),
		TRAINERID VARCHAR2(200),
		TRADECONTENT VARCHAR2(3000),
		UPLOAD DATE DEFAULT SYSDATE,
		CHECKREVIEW NUMBER DEFAULT 0,
		CONSTRAINT DG_TRADE_PK PRIMARY KEY(TRADENUM)
	);

	SELECT * FROM DG_TRADE;
	INSERT INTO DG_TRADE(TRADENUM, USERID, TRADECONTENT, UPLOAD) VALUES(2000, 'test', 'test', SYSDATE);
	
-- 검색 
-- 테이블
	CREATE TABLE DG_KEYWORD(
	   KEYWORD VARCHAR2(3000) PRIMARY KEY,
	   CNT NUMBER(38)
	);

-- 중복검사 뷰(미완성)
	CREATE VIEW ID_VIEW AS SELECT A.MEMBERID AS USERID FROM (SELECT MEMBERID FROM DG_MEMBER
		UNION ALL SELECT TRAINERID FROM DG_TRAINER
		UNION ALL SELECT ADMINID FROM DG_ADMIN) A;
	
	SELECT * FROM ID_VIEW;