-- 첨부 파일
-- 시퀀스
	CREATE SEQUENCE FILENAME_SEQ;
-- 테이블
	CREATE TABLE FILENAME(
		CATEGORYNUM NUMBER,
		BOARDNUM NUMBER,
		USERID VARCHAR2(200),
		FILENAME VARCHAR2(3000),
		CONSTRAINT FILE_PK PRIMARY KEY(FILENAME)
	);
	
	SELECT * FROM FILENAME;
	
-- PROFILENAME(임지혁)
-- 시퀀스
	CREATE SEQUENCE DG_PROFILE_SEQ;
-- 테이블
	CREATE TABLE PROFILENAME(
		CATEGORYNUM NUMBER,
		BOARDNUM NUMBER,
		FILENAME VARCHAR2(3000),
		TRAINERID VARCHAR2(200),
		CONSTRAINT PROFILENAME_PK PRIMARY KEY(FILENAME),
		CONSTRAINT DG_PROFILENAME_TRAINER_FK FOREIGN KEY(TRAINERID) REFERENCES DG_TRAINER(TRAINERID) ON DELETE CASCADE
	); 

	SELECT * FROM PROFILENAME;

-- DG_SNS(임지혁)
-- 시퀀스
	CREATE SEQUENCE DG_SNS_SEQ;
-- 테이블
	CREATE TABLE SNSFILENAME(
		CATEGORYNUM NUMBER,
		BOARDNUM NUMBER,
		FILENAME VARCHAR2(3000),
		TRAINERID VARCHAR2(200),
		CONSTRAINT SNSFILENAME_PK PRIMARY KEY(FILENAME),
		CONSTRAINT DG_SNSFILENAME_TRAINER_FK FOREIGN KEY(TRAINERID) REFERENCES DG_TRAINER(TRAINERID) ON DELETE CASCADE
	);

	SELECT * FROM SNSFILENAME;

	SELECT * FROM SNSFILENAME WHERE FILENAME = '%EB%8D%B0%EC%9A%B0%EC%8A%A4%EB%AA%A8%EC%9E%90.PNG';
	DELETE FROM SNSFILENAME WHERE FILENAME = '%EB%8D%B0%EC%9A%B0%EC%8A%A4%EB%AA%A8%EC%9E%90.PNG';

	DROP TRIGGER TRAINERID_TGR;

	SELECT text FROM  user_source where name = 'TRAINERID_TGR' ;