-- 회원 계정
-- 테이블
	CREATE TABLE DG_MEMBER(
		MEMBERID VARCHAR2(200),
		MEMBERPW VARCHAR2(300),
		MEMBERPHONE VARCHAR2(100),
		MEMBERPOINT NUMBER DEFAULT 0,
		CONSTRAINT DG_MEMBER_PK PRIMARY KEY(MEMBERID)
	);

	SELECT * FROM DG_MEMBER;