-- 회원 회원가입
-- 끝
CREATE TABLE DG_MEMBER(
	MEMBERID VARCHAR2(200),
	MEMBERPW VARCHAR2(300),
	MEMBERPHONE VARCHAR2(100),
	MEMBERPOINT NUMBER DEFAULT 0,
	MEMBERTRADE VARCHAR2(2000),
	CONSTRAINT DG_MEMBER_PK PRIMARY KEY(MEMBERID)
);


-- 회원 사진 게시판
-- 회원이 탈퇴하면 회원 사진 게시판에 회원이 올린 게시글도 삭제
-- 끝
CREATE SEQUENCE DG_PHOTO_SEQ;
CREATE TABLE DG_PHOTOBOARD(
	UPLOAD DATE DEFAULT SYSDATE,
	PHOTOBOARDNUM NUMBER,
	PHOTOBOARDTITLE VARCHAR2(1000),
	MEMBERID VARCHAR2(200),
	PHOTOBOARDCONTENT VARCHAR2(3000),
	/*PHOTOFILENAME VARCHAR2(3000),*/
	CONSTRAINT DG_PHOTO_PK PRIMARY KEY(PHOTOBOARDNUM),
	CONSTRAINT DG_PHOTO_FK FOREIGN KEY(MEMBERID) REFERENCES DG_MEMBER(MEMBERID) ON DELETE CASCADE
);

-- 회원 사진 게시판 댓글
-- 회원이 올린 게시글이 삭제되면 게시판 댓글도 삭제
-- 끝
CREATE SEQUENCE DG_MREPLY_SEQ;
CREATE TABLE DG_MREPLY(
	MREPLYNUM NUMBER,
	UPLOAD DATE DEFAULT SYSDATE,
	PHOTONUM NUMBER,
	MEMBERID VARCHAR2(200),
	MREPLYCONTENT VARCHAR2(3000),
	CONSTRAINT DG_MREPLY_PK PRIMARY KEY(MREPLYNUM),
	CONSTRAINT DG_MREPLY_MEMBER_FK FOREIGN KEY(MEMBERID) REFERENCES DG_MEMBER(MEMBERID),
	CONSTRAINT DG_MREPLY_PHOTO_FK FOREIGN KEY(PHOTONUM) REFERENCES DG_PHOTOBOARD(PHOTOBOARDNUM) ON DELETE CASCADE
);

-- 리뷰 쓰기
-- 끝
CREATE SEQUENCE DG_REVIEW_SEQ;
CREATE TABLE DG_REVIEW(
	UPLOAD DATE DEFAULT SYSDATE,
	REVIEWNUM NUMBER,
	TRAINERID VARCHAR2(200),
	MEMBERID VARCHAR2(200),
	REVIEWCONTENT VARCHAR2(3000),
	CONSTRAINT DG_REVIEW_PK PRIMARY KEY(REVIEWNUM),
	CONSTRAINT DG_REVIEW_TRAINER_FK FOREIGN KEY(TRAINERID) REFERENCES DG_MEMBER(TRAINERID) ON DELETE CASCADE
	CONSTRAINT DG_REVIEW_MEMBER_FK FOREIGN KEY(MEMBERID) REFERENCES DG_MEMBER(MEMBERID) ON DELETE CASCADE
);

-- 끝
CREATE SEQUENCE FILENAME_SEQ;
CREATE TABLE FILENAME(
	CATEGORYNUM NUMBER,
	BOARDNUM NUMBER,
	FILENAME VARCHAR2(3000),
	CONSTRAINT FILE_PK PRIMARY KEY(FILENAME),
	CONSTRAINT FILE_REPORT_FK FOREIGN KEY(REPORTNUM) REFERENCES DG_ADMIN(REPORTNUM) ON DELETE CASCADE,
	CONSTRAINT FILE_REVIEW_FK FOREIGN KEY(BOARDNUM) REFERENCES DG_REVIEW(REVIEWNUM) ON DELETE CASCADE,
	CONSTRAINT FILE_PHOTOBOARD_FK FOREIGN KEY(BOARDNUM) REFERENCES DG_PHOTOBOARD(PHOTOBOARDNUM) ON DELETE CASCADE,
	CONSTRAINT FILE_TPAGE_FK FOREIGN KEY(BOARDNUM) REFERENCES DG_TPAGE(TPAGENUM) ON DELETE CASCADE,
	CONSTRAINT FILE_QNA_FK FOREIGN KEY(BOARDNUM) REFERENCES DG_QNA(QNANUM) ON DELETE CASCADE
);

