-- 회원 계정
-- 테이블
	CREATE TABLE DG_MEMBER(
		MEMBERID VARCHAR2(200),
		MEMBERPW VARCHAR2(300),
		MEMBERPHONE VARCHAR2(100),
		MEMBERPOINT NUMBER DEFAULT 0,
		CONSTRAINT DG_MEMBER_PK PRIMARY KEY(MEMBERID)
	);

	SELECT * FROM DG_MEMBER;

-- 사진 게시판
-- 시퀀스
	CREATE SEQUENCE DG_PHOTO_SEQ;
-- 테이블
	CREATE TABLE DG_PHOTOBOARD(
		UPLOAD DATE DEFAULT SYSDATE,
		PHOTOBOARDNUM NUMBER,
		PHOTOBOARDTITLE VARCHAR2(1000),
		MEMBERID VARCHAR2(200),
		PHOTOBOARDCONTENT VARCHAR2(3000),
		READCOUNT NUMBER,
		REPLYNUM NUMBER,
		CONSTRAINT DG_PHOTO_PK PRIMARY KEY(PHOTOBOARDNUM),
		CONSTRAINT DG_PHOTO_FK FOREIGN KEY(MEMBERID) REFERENCES DG_MEMBER(MEMBERID) ON DELETE CASCADE
	);

	SELECT * FROM DG_PHOTOBOARD;

-- 사진 게시판 댓글
-- 시퀀스
	CREATE SEQUENCE DG_MREPLY_SEQ;
-- 테이블
	CREATE TABLE DG_MREPLY(
		MREPLYNUM NUMBER,
		UPLOAD DATE DEFAULT SYSDATE,
		PHOTONUM NUMBER,
		MEMBERID VARCHAR2(200),
		MREPLYCONTENT VARCHAR2(3000),
		CONSTRAINT DG_MREPLY_PK PRIMARY KEY(MREPLYNUM),
		CONSTRAINT DG_MREPLY_MEMBER_FK FOREIGN KEY(MEMBERID) REFERENCES DG_MEMBER(MEMBERID),
		CONSTRAINT DG_MREPLY_PHOTO_FK FOREIGN KEY(PHOTONUM) REFERENCES DG_PHOTOBOARD(PHOTOBOARDNUM) ON DELETE CASCADE
	);

	SELECT * FROM DG_MREPLY;

-- 리뷰 게시판
-- 시퀀스
	CREATE SEQUENCE DG_REVIEW_SEQ;
-- 테이블
	CREATE TABLE DG_REVIEW(
		UPLOAD DATE DEFAULT SYSDATE,
		REVIEWNUM NUMBER,
		TRAINERID VARCHAR2(200),
		MEMBERID VARCHAR2(200),
		REVIEWCONTENT VARCHAR2(3000),
		CONSTRAINT DG_REVIEW_PK PRIMARY KEY(REVIEWNUM),
		CONSTRAINT DG_REVIEW_TRAINER_FK FOREIGN KEY(TRAINERID) REFERENCES DG_TRAINER(TRAINERID) ON DELETE CASCADE,
		CONSTRAINT DG_REVIEW_MEMBER_FK FOREIGN KEY(MEMBERID) REFERENCES DG_MEMBER(MEMBERID) ON DELETE CASCADE
	);

	SELECT * FROM DG_REVIEW;

-- 첨부 파일
-- 시퀀스
	CREATE SEQUENCE FILENAME_SEQ;
-- 테이블
	CREATE TABLE FILENAME(
		CATEGORYNUM NUMBER,
		BOARDNUM NUMBER,
		USERID VARCHAR2(200),
		FILENAME VARCHAR2(3000),
		CONSTRAINT FILE_PK PRIMARY KEY(FILENAME)
	);
	
	SELECT * FROM FILENAME;