-- 문의 게시판
-- 회원이 탈퇴하면 회원이 남긴 문의도 삭제
CREATE SEQUENCE DG_QNA_SEQ;
CREATE TABLE DG_QNA(
	QNANUM NUMBER,
	UPLOAD DATE DEFAULT SYSDATE,
	QNATITLE VARCHAR2(500),
	MEMBERID VARCHAR2(200),
	QNACONTENT VARCHAR2(3000),
	READCOUNT NUMBER,
	CONSTRAINT DG_QNA_PK PRIMARY KEY(QNANUM),
	CONSTRAINT DG_QNA_FK FOREIGN KEY(MEMBERID) REFERENCES DG_MEMBER(MEMBERID) ON DELETE CASCADE
);


-- 문의 게시판 댓글
-- 문의 글이 삭제되면 문의 글에 대한 댓글도 삭제
CREATE SEQUENCE DG_QREPLY_SEQ;
CREATE TABLE DG_QREPLY(
	QREPLYNUM NUMBER(10),
	UPLOAD DATE DEFAULT SYSDATE,
	QNANUM NUMBER(10),
	MEMBERID VARCHAR2(100),
	QREPLYCONTENT VARCHAR2(3000),
	CONSTRAINT DG_QREPLY_PK PRIMARY KEY(QREPLYNUM),
	CONSTRAINT DG_QREPLY_QNA_FK FOREIGN KEY(QNANUM) REFERENCES DG_QNA(QNANUM) ON DELETE CASCADE,
	CONSTRAINT DG_QREPLY_MEMBER_FK FOREIGN KEY(MEMBERID) REFERENCES DG_MEMBER(MEMBERID)
);


