-- 문의 게시판
-- 시퀀스
	CREATE SEQUENCE DG_QNA_SEQ;
-- 테이블
	CREATE TABLE DG_QNA(
		QNANUM NUMBER,
		UPLOAD DATE DEFAULT SYSDATE,
		QNATITLE VARCHAR2(500),
		MEMBERID VARCHAR2(200),
		QNACONTENT VARCHAR2(3000),
		READCOUNT NUMBER,
		CONSTRAINT DG_QNA_PK PRIMARY KEY(QNANUM)
	);

	SELECT * FROM DG_QNA;

-- 문의 게시판 댓글
-- 시퀀스
	CREATE SEQUENCE DG_QREPLY_SEQ;
-- 테이블
	CREATE TABLE DG_QREPLY(
		QREPLYNUM NUMBER(10),
		UPLOAD DATE DEFAULT SYSDATE,
		QNANUM NUMBER(10),
		MEMBERID VARCHAR2(100),
		QREPLYCONTENT VARCHAR2(3000),
		CONSTRAINT DG_QREPLY_PK PRIMARY KEY(QREPLYNUM)
	);
	
	SELECT * FROM DG_QREPLY;