-- 신고게시판
-- 시퀀스
	CREATE SEQUENCE DG_REPORT_SEQ;
-- 테이블
	CREATE TABLE DG_REPORT(
		REPORTNUM NUMBER,
		REPORTTITLE VARCHAR2(1000),
		REPORTID VARCHAR2(500),
		REPORTCONTENT VARCHAR2(3000),
		UPLOAD DATE DEFAULT SYSDATE,
		READCOUNT NUMBER,
		CONSTRAINT DG_REPORT_PK PRIMARY KEY(REPORTNUM)
	);

	SELECT * FROM DG_REPORT;

-- 관리자 계정
-- 테이블
	CREATE TABLE DG_ADMIN(
		ADMINID VARCHAR2(500),
		ADMINPW VARCHAR2(500),
		CONSTRAINT DG_ADMIN_PK PRIMARY KEY(ADMINID)
	);

	INSERT INTO DG_ADMIN VALUES('admin', '1234');

