-- 신고하기 시퀀스
CREATE SEQUENCE DG_REPORT_SEQ;
-- 신고하기 테이블
-- 끝
CREATE TABLE DG_REPORT(
   REPORTNUM NUMBER,
   REPORTTITLE VARCHAR2(1000),
   REPORTID VARCHAR2(500),
   REPORTCONTENT VARCHAR2(3000),
   UPLOAD DATE DEFAULT SYSDATE,
   READCOUNT NUMBER,
   CONSTRAINT DG_REPORT_PK PRIMARY KEY(REPORTNUM),
   CONSTRAINT REPORT_MEMBER_FK FOREIGN KEY(REPORTID) REFERENCES DG_MEMBER(MEMBERID),
   CONSTRAINT REPORT_TRAINER_FK FOREIGN KEY(REPORTID) REFERENCES DG_TRAINER(TRAINERID)
);

CREATE TABLE DG_ADMIN(
	ADMINID VARCHAR2(500),
	ADMINPW VARCHAR2(500),
	CONSTRAINT DG_ADMIN_PK PRIMARY KEY(ADMINID)
);

INSERT INTO DG_ADMIN VALUES('admin', '1234');
