CREATE SEQUENCE DG_TRAINER_SEQ;
-- 트레이너 회원가입
CREATE TABLE DG_TRAINER(
   TRAINERID VARCHAR2(200),
   TRAINERPW VARCHAR2(300),
   TRAINERNAME VARCHAR2(200),
   TRAINERPHONENUM VARCHAR2(100),
   TRAINERGENDER VARCHAR(10),
   TRAINEREMAIL VARCHAR2(300),
   TRAINERACCOUNT VARCHAR2(300),
   TRAINERADDRESSZIPCODE VARCHAR2(500),
   TRAINERADDRESS VARCHAR2(500),
   TRAINERADDRESSDETAIL VARCHAR2(500),
   TRAINERTRADE VARCHAR2(2000),
   TRAINERPOINT NUMBER DEFAULT 0,
   TRAINERNUM NUMBER UNIQUE NOT NULL,     
   TRAINERCONTENT VARCHAR2(3000),
   TRAINERURL VARCHAR2(500),
   TRAINERLIKE NUMBER,
   CONSTRAINT DG_TRAINER_PK PRIMARY KEY(TRAINERID)
);

INSERT INTO DG_TRAINER(TRAINERID, TRAINERPW, TRAINERNUM) VALUES('test2', '123123', 1);

--DROP TABLE DG_TRAINER;
--DROP TABLE DG_REVIEW;
--DROP TABLE DG_REPORT;
--DROP TABLE DG_QREPLY;
--DROP TABLE DG_PHOTOBOARD;
--DROP TABLE DG_QNA;
--DROP TABLE DG_MREPLY;
--DROP TABLE DG_MEMBER;
