-- 트레이너 회원가입
CREATE TABLE DG_TRAINER(
   TRAINERID VARCHAR2(200),
   TRAINERPW VARCHAR2(300),
   TRAINERNAME VARCHAR2(200),
   TRAINERPHONENUM VARCHAR2(100),
   TRAINERGENDER VARCHAR(10),
   TRAINEREMAIL VARCHAR2(300),
   TRAINERACCOUNT VARCHAR2(300),
   TRAINERADDRESSZIPCODE VARCHAR2(500),
   TRAINERADDRESS VARCHAR2(500),
   TRAINERADDRESSDETAIL VARCHAR2(500),
   TRAINERTRADE VARCHAR2(2000),
   TRAINERPOINT NUMBER DEFAULT 0,
   TRAINERNUM NUMBER,     
   TRAINERCONTENT VARCHAR2(3000),
   TRAINERURL VARCHAR2(500),
   TRAINERLIKE NUMBER,
   CONSTRAINT DG_TRAINER_PK PRIMARY KEY(TRAINERID)
);

