CREATE SEQUENCE USER_SEQ
INCREMENT BY 1 --1씩 증가
START WITH 1 --1부터 시작
MINVALUE 1 --최소값 1
MAXVALUE 1000 --최대값 1000;

CREATE TABLE USER_TBL(--JDBC에서 접근할 때 키워드랑 테이블 이름이 같으면 ""를 써줘야 함
	USER_NUMBER NUMBER NOT NULL,--NUMBER에 ()가 없는 이유는 
	ID VARCHAR2(100),
	PW VARCHAR2(100),
	NAME VARCHAR2(100),
	AGE NUMBER,
	PHONENUMBER VARCHAR2(15),
	CONSTRAINT USER_PK PRIMARY KEY(ID)
);

SELECT * FROM USER_TBL;

 