-- 전체보기 시퀀스
CREATE SEQUENCE DG_ADMIN_SEQ;
-- 전체보기 테이블
CREATE TABLE DG_ADMIN( 
	ADMINNUM NUMBER,
	MEMBERID VARCHAR2(200),
	TRAINERID VARCHAR2(200),
	QNANUM NUMBER,
	QREPLYNUM NUMBER,
	TPAGENUM NUMBER,
	TREPLYNUM NUMBER,
	PHOTONUM NUMBER,
	MREPLYNUM NUMBER,
	REVIEWNUM NUMBER,
	CONSTRAINT DG_ADMIN_PK PRIMARY KEY(ADMINNUM),
	CONSTRAINT DG_ADMIN_MEMBER_FK FOREIGN KEY(MEMBERID) REFERENCES DG_MEMBER(MEMBERID),
	CONSTRAINT DG_ADMIN_TRAINER_FK FOREIGN KEY(TRAINERID) REFERENCES DG_TRAINER(TRAINERID),
	CONSTRAINT DG_ADMIN_QNA_FK FOREIGN KEY(QNANUM) REFERENCES DG_QNA(QNANUM),
	CONSTRAINT DG_ADMIN_QREPLY_FK FOREIGN KEY(QREPLYNUM) REFERENCES DG_QREPLY(QREPLYNUM),
	CONSTRAINT DG_ADMIN_TPAGE_FK FOREIGN KEY(TPAGENUM) REFERENCES DG_TPAGE(TPAGENUM),
	CONSTRAINT DG_ADMIN_TREPLY_FK FOREIGN KEY(TREPLYNUM) REFERENCES DG_TREPLY(TREPLYNUM),
	CONSTRAINT DG_ADMIN_PHOTO_FK FOREIGN KEY(PHOTONUM) REFERENCES DG_PHOTO(PHOTONUM),
	CONSTRAINT DG_ADMIN_MREPLY_FK FOREIGN KEY(MREPLYNUM) REFERENCES DG_MREPLY(MREPLYNUM),
	CONSTRAINT DG_ADMIN_REVIEW_FK FOREIGN KEY(REVIEWNUM) REFERENCES DG_REVIEW(REVIEWNUM)
);

--삭제정보 시퀀스--
CREATE SEQUENCE DG_REMOVE_SEQ;
--삭제 테이블--
CREATE TABLE DG_REMOVE( 
	ADMINNUM NUMBER,
	MEMBERID VARCHAR2(200),
	TRAINERID VARCHAR2(200),
	RQNANUM NUMBER,
	RQREPLYNUM NUMBER,
	RTREPLYNUM NUMBER,
	RPHOTONUM NUMBER,
	RMREPLYNUM NUMBER,
	RREVIEWNUM NUMBER,
	CONSTRAINT DG_REMOVE_PK PRIMARY KEY(ADMINNUM) 
);