-- 회원 회원가입
CREATE TABLE DG_MEMBER(
	MEMBERID VARCHAR2(200),
	MEMBERPW VARCHAR2(300),
	MEMBERNAME VARCHAR2(200),
	MEMBERPHONENUM VARCHAR2(100),
	MEMBERGENDER VARCHAR2(10),
	MEMBEREMAIL VARCHAR2(300),
	MEMBERADDRESS VARCHAR2(500),
	MEMBERTRADE VARCHAR2(2000),
	MEMBERPOINT NUMBER DEFAULT 0,
	CONSTRAINT DG_MEMBER_PK PRIMARY KEY(MEMBERID)
);

-- 회원 사진 게시판
-- 회원이 탈퇴하면 회원 사진 게시판에 회원이 올린 게시글도 삭제
CREATE SEQUENCE DG_PHOTO_SEQ;
CREATE TABLE DG_PHOTO(
	PHOTONUM NUMBER,
	MEMBERID VARCHAR2(200),
	PHOTOCONTENT VARCHAR2(3000),
	PHOTOFILENAME VARCHAR2(3000),
	CONSTRAINT DG_PHOTO_PK PRIMARY KEY(PHOTONUM),
	CONSTRAINT DG_PHOTO_FK FOREIGN KEY(MEMBERID) REFERENCES DG_MEMBER(MEMBERID) ON DELETE CASCADE
);

-- 회원 사진 게시판 댓글
-- 회원이 올린 게시글이 삭제되면 게시판 댓글도 삭제
CREATE SEQUENCE DG_MREPLY_SEQ;
CREATE TABLE DG_MREPLY(
	MREPLYNUM NUMBER,
	PHOTONUM NUMBER,
	MEMBERID VARCHAR2(200),
	MREPLYCONTENT VARCHAR2(3000),
	CONSTRAINT DG_MREPLY_PK PRIMARY KEY(MREPLYNUM),
	CONSTRAINT DG_MREPLY_MEMBER_FK FOREIGN KEY(MEMBERID) REFERENCES DG_MEMBER(MEMBERID),
	CONSTRAINT DG_MREPLY_PHOTO_FK FOREIGN KEY(PHOTONUM) REFERENCES DG_PHOTO(PHOTONUM) ON DELETE CASCADE
);

-- 리뷰 쓰기
-- 회원이 탈퇴하면 회원이 올린 리뷰도 삭제(음?)
CREATE SEQUENCE DG_REVIEW_SEQ;
CREATE TABLE DG_REVIEW(
	REVIEWNUM NUMBER,
	MEMBERID VARCHAR2(200),
	REVIEWCONTENT VARCHAR2(3000),
	REVIEWFILENAME VARCHAR2(3000),
	CONSTRAINT DG_REVIEW_PK PRIMARY KEY(REVIEWNUM),
	CONSTRAINT DG_REVIEW_FK FOREIGN KEY(MEMBERID) REFERENCES DG_MEMBER(MEMBERID) ON DELETE CASCADE
);