-- 트레이너 회원가입
CREATE TABLE DG_TRAINER(
	TRAINERID VARCHAR2(200),
	TRAINERPW VARCHAR2(300),
	TRAINERNAME VARCHAR2(200),
	TRAINERPHONENUM VARCHAR2(100),
	TRAINERGENDER VARCHAR(10),
	TRAINEREMAIL VARCHAR2(300),
	TRAINERACCOUNT VARCHAR2(300),
	TRAINERADDRESS VARCHAR2(500),
	TRAINERPOINT NUMBER DEFAULT 0,
	TRAINERTRADE VARCHAR2(2000),
	TRAINERFILENAME VARCHAR2(2000),
	CONSTRAINT DG_TRAINER_PK PRIMARY KEY(TRAINERID)
);

-- 트레이너 마이페이지
-- 트레이너가 회원 탈퇴하면 마이페이지 글도 삭제
CREATE SEQUENCE DG_TPAGE_SEQ;
CREATE TABLE DG_TPAGE(
	TPAGENUM NUMBER,
	TRAINERID VARCHAR2(200),
	TPAGECONTENT VARCHAR2(3000),
	TPAGEFILENAME VARCHAR2(3000),
	CONSTRAINT DG_TPAGE_PK PRIMARY KEY(TPAGENUM),
	CONSTRAINT DG_TPAGE_FK FOREIGN KEY(TRAINERID) REFERENCES DG_TRAINER(TRAINERID) ON DELETE CASCADE
);

-- 트레이너 마이페이지 댓글
-- 트레이너 마이페이지 글이 삭제되면 댓글도 삭제
CREATE SEQUENCE DG_TREPLY_SEQ;
CREATE TABLE DG_TREPLY(
	TREPLYNUM NUMBER,
	TPAGENUM NUMBER,
	MEMBERID VARCHAR2(100),
	TREPLYCONTENT VARCHAR2(4000),
	CONSTRAINT DG_TREPLY_PK PRIMARY KEY(TREPLYNUM),
	CONSTRAINT DG_TREPLY_MEMBER_FK FOREIGN KEY(MEMBERID) REFERENCES DG_MEMBER(MEMBERID),
	CONSTRAINT DG_TREPLY_TPAGE_FK FOREIGN KEY(TPAGENUM) REFERENCES DG_TPAGE(TPAGENUM) ON DELETE CASCADE
);