CREATE SEQUENCE MEMBER_SEQ;

CREATE TABLE TBL_MEMBER(
	NUM NUMBER NOT NULL,
	NAME VARCHAR2(200),
	BIRTHDAY DATE,
	CONSTRAINT MEMBER_PK PRIMARY KEY(NUM)
);

SELECT * FROM TBL_MEMBER;

INSERT INTO TBL_MEMBER VALUES(MEMBER_SEQ.NEXTVAL, '홍길동', TO_DATE('1991-01-01', 'YYYY-MM-DD'));
INSERT INTO TBL_MEMBER VALUES(MEMBER_SEQ.NEXTVAL, '홍길동', TO_DATE('1991-01-05', 'YYYY-MM-DD'));

CREATE TABLE TABLE_MEMBER(
	NUM NUMBER PRIMARY KEY,
	ID VARCHAR2(200)
);

SELECT * FROM TABLE_MEMBER;

INSERT INTO TABLE_MEMBER VALUES(1, 'hds1234');
