

SELECT * FROM TABLE_MEMBER;

DROP TABLE TABLE_MEMBER;

CREATE TABLE TABLE_MEMBER(
	NUM NUMBER PRIMARY KEY,
	ID VARCHAR2(500),
	NAME VARCHAR2(500),
	PASSWORD VARCHAR2(500),
	GENDER VARCHAR2(50),
	ZIPCODE VARCHAR2(50),
	ADDRESS VARCHAR2(500),
	ADDRESSDETAIL VARCHAR2(500),
	ADDRESSETC VARCHAR2(500)
);

SELECT * FROM TABLE_MEMBER;
