CREATE SEQUENCE BOARD_SEQ;

CREATE TABLE TABLE_BOARD(
	BOARDNUM NUMBER(10),
	BOARDTITLE VARCHAR2(1000),
	BOARDCONTENT VARCHAR2(3000),
	BOARDID VARCHAR2(100),
	BOARDDATE DATE,
	CONSTRAINT BOARD_PK PRIMARY KEY(BOARDNUM),
	CONSTRAINT BOARD_FK FOREIGN KEY(BOARDID) REFERENCES TABLE_MEMBER(MEMBERID)
);

ALTER TABLE TABLE_BOARD ADD READCOUNT NUMBER(10) DEFAULT 0;

INSERT INTO TABLE_BOARD VALUES(BOARD_SEQ.NEXTVAL, 'test1', '냉무', 'iu', SYSDATE, 0);

SELECT * FROM TABLE_BOARD;

CREATE TABLE TABLE_FILES(
	FILENAME VARCHAR2(2000),
	BOARDNUM NUMBER(10),
	CONSTRAINT FILES_PK PRIMARY KEY(FILENAME),
	CONSTRAINT FILES_FK FOREIGN KEY(BOARDNUM) REFERENCES TABLE_BOARD(BOARDNUM)
);

SELECT * FROM TABLE_FILES;

INSERT INTO TABLE_FILES VALUES('test2', 58);

