CREATE SEQUENCE REPLY_SEQ;

CREATE TABLE TABLE_REPLY(
	REPLYNUM NUMBER(10),
	BOARDNUM NUMBER(10),
	MEMBERID VARCHAR2(100),
	REPLYCONTENT VARCHAR2(4000),
	CONSTRAINT REPLY_PK PRIMARY KEY(REPLYNUM),
	CONSTRAINT REPLY_BOARD_FK FOREIGN KEY(BOARDNUM) REFERENCES TABLE_BOARD(BOARDNUM),
	CONSTRAINT REPLY_MEMBER_FK FOREIGN KEY(MEMBERID) REFERENCES TABLE_MEMBER(MEMBERID)
);

ALTER TABLE TABLE_REPLY DROP CONSTRAINT REPLY_BOARD_FK;

ALTER TABLE TABLE_REPLY ADD CONSTRAINT REPLY_BOARD_FK
FOREIGN KEY(BOARDNUM) REFERENCES TABLE_BOARD(BOARDNUM)
ON DELETE CASCADE;

SELECT * FROM TABLE_REPLY;